#!/usr/bin/env Rscript
# -----------------------------------------------------------------------------
# Protocol Report Template — REACH TOR Template Integration
#
# The Word report generated by Protocol$generate_report() and
# SurveyProtocol$generate_report() is now based on the REACH Terms of
# Reference (TOR) template:
#
#   resources/REACH_TOR_Template_ 2023-06_clean_ENGLISH.docx
#
# A copy of this file is bundled with the package at:
#
#   inst/resources/reach_tor_template.docx
#
# When generate_report() runs it will:
#   1. Load reach_tor_template.docx (inheriting all its styles, branding,
#      headers, and footers).
#   2. Replace key placeholder strings in the Executive Summary table:
#        [Research Cycle title]  → assessment_title
#        [Country]               → country_name (everywhere it appears)
#        [Release date]          → today's date (dd/mm/yyyy)
#        [Version number]        → protocol version ("v1.0")
#        [Specify name(s) here]  → country_name
#        General / Specific Objective cells → text from objectives
#        Geographic Coverage cell            → country_name
#        Research Questions cell             → short_objective IDs
#   3. Insert a "Protocol Data" section heading immediately before the
#      "Rationale" section (i.e. directly after the Executive Summary table).
#   4. Append — in order — within that new section:
#        "Research Objectives"  (heading 2 + flextable of all objectives)
#        "Data Collection Tools" (heading 2 + per-tool heading 3 + indicator table)
#        "Sampling Design"       (SurveyProtocol only — strata + PSU tables)
#
# The rest of the REACH TOR template (Rationale, Methodology, Ethics,
# Roles & Responsibilities, DAP, DMP, M&E) is left intact so practitioners
# can complete those sections manually.
#
# -----------------------------------------------------------------------------
# To refresh the bundled template if the source document has been updated:
#
#   file.copy(
#     from = "resources/REACH_TOR_Template_ 2023-06_clean_ENGLISH.docx",
#     to   = "inst/resources/reach_tor_template.docx",
#     overwrite = TRUE
#   )
#
# No R packages are required to run that one-liner.
# -----------------------------------------------------------------------------
