# --------------------------------------------------------------------------------
# R6 Class: Tool (Base Class for XLSForm Management)
# --------------------------------------------------------------------------------
#
# This module provides the base Tool R6 class for managing XLSForm data used
# in Kobo, ODK, and other data collection applications.
#
# The Tool class provides the foundation for the tool class hierarchy:
# - Tool: Base class (this file)
# - HouseholdTool: Subclass for household survey tools (class_household_tool.R)
# - KeyInformantTool: Subclass for key informant interview tools (class_key_informant_tool.R)
# - ObservationTool: Subclass for observation/checklist tools (class_observation_tool.R)
#
# Key Features:
# - Load and manage survey and choices sheets from XLSForm
# - Filter questions by selected indicators
# - Validate XLSForm structure according to specification
# - Modify select question options and choices
#
# XLSForm Reference: https://xlsform.org/en/
# --------------------------------------------------------------------------------

# --------------------------------------------------------------------------------
# Null-coalescing operator (if not already available)
# This is also defined in utils_session.R but we define it here to ensure
# availability regardless of file load order
# --------------------------------------------------------------------------------

if (!exists("%||%", mode = "function")) {
  `%||%` <- function(x, y) {
    if (is.null(x)) y else x
  }
}

# --------------------------------------------------------------------------------
# R6 Class: Tool (Base Class)
# --------------------------------------------------------------------------------

#' @title Tool R6 Class for XLSForm Management
#' @description
#' Base R6 class for managing XLSForm data collection tools used with
#' Kobo, ODK, and other mobile data collection platforms.
#'
#' An XLSForm consists of at least two sheets:
#' - survey: Contains the form structure (questions, groups, etc.)
#' - choices: Contains choice lists for select questions
#' - settings: Contains form-level settings (title, language, version)
#'
#' This class maintains both master (template) and modified (filtered) versions
#' of the survey and choices sheets. The master copies are loaded from a default
#' XLSForm file on initialization; the modified copies are generated by calling
#' the filter methods.
#'
#' This class provides methods for:
#' - Loading and storing XLSForm data (master and modified)
#' - Filtering the master survey by modules/indicators
#' - Filtering the master choices to match the modified survey
#' - Safely updating specific choice lists with new values
#' - Changing the default language in settings
#' - Validating the modified survey against available choices
#' - Validating structure according to XLSForm specification
#'
#' @importFrom readxl read_excel
#' @export
Tool <- R6::R6Class(

"Tool",
public = list(

  #' @field survey Data frame containing the survey sheet of the XLSForm.
  survey = NULL,

  #' @field choices Data frame containing the choices sheet of the XLSForm.
  choices = NULL,

  #' @field settings Data frame containing the settings sheet of the XLSForm.
  settings = NULL,

  # ------------------------------------------------------------------------
  # Initialization
  # ------------------------------------------------------------------------

  #' @description
  #' Initialize a new Tool object.
  #'
  #' @param name Optional name for the tool.
  #' @param survey Optional data.frame containing the survey sheet (master).
  #' @param choices Optional data.frame containing the choices sheet (master).
  #' @param settings Optional data.frame containing the settings sheet.
  #' @return A new Tool object.
  initialize = function(name = NULL,
                        survey = NULL,
                        choices = NULL,
                        settings = NULL) {
    private$.name <- name %||% "Untitled Tool"
    private$.created_at <- Sys.time()
    private$.modified_at <- Sys.time()
    private$.tool_type <- "generic"

    # Initialize empty data frames with required columns if not provided
    self$survey <- if (!is.null(survey)) {
      private$.validate_survey_structure(survey)
      survey
    } else {
      private$.create_empty_survey()
    }

    self$choices <- if (!is.null(choices)) {
      private$.validate_choices_structure(choices)
      choices
    } else {
      private$.create_empty_choices()
    }

    self$settings <- if (!is.null(settings)) {
      settings
    } else {
      private$.create_empty_settings()
    }

    private$.modified_survey <- NULL
    private$.modified_choices <- NULL
    private$.selected_indicators <- character(0)
    private$.validation_errors <- list()
    private$.metadata <- list()

    invisible(self)
  },

  # ------------------------------------------------------------------------
  # Data Accessors
  # ------------------------------------------------------------------------

  #' @description
  #' Get the tool name.
  #' @return Character string with tool name.
  get_name = function() {
    private$.name
  },

  #' @description
  #' Set the tool name.
  #' @param name Character string for the tool name.
  #' @return Invisibly returns self for method chaining.
  set_name = function(name) {
    if (!is.character(name) || length(name) != 1 || nchar(name) == 0) {
      stop("Tool name must be a non-empty character string")
    }
    private$.name <- name
    private$.touch()
    invisible(self)
  },

  #' @description
  #' Get the tool type.
  #' @return Character string indicating the tool type.
  get_tool_type = function() {
    private$.tool_type
  },

  #' @description
  #' Get the survey sheet data.
  #' @return Data frame containing the survey sheet.
  get_survey = function() {
    self$survey
  },

  #' @description
  #' Set the survey sheet data.
  #' @param survey Data frame containing survey data.
  #' @param validate Logical, whether to validate structure (default TRUE).
  #' @return Invisibly returns self for method chaining.
  set_survey = function(survey, validate = TRUE) {
    if (!is.data.frame(survey)) {
      stop("Survey must be a data.frame")
    }
    if (validate) {
      private$.validate_survey_structure(survey)
    }
    self$survey <- survey
    private$.touch()
    invisible(self)
  },

  #' @description
  #' Get the choices sheet data.
  #' @return Data frame containing the choices sheet.
  get_choices = function() {
    self$choices
  },

  #' @description
  #' Set the choices sheet data.
  #' @param choices Data frame containing choices data.
  #' @param validate Logical, whether to validate structure (default TRUE).
  #' @return Invisibly returns self for method chaining.
  set_choices = function(choices, validate = TRUE) {
    if (!is.data.frame(choices)) {
      stop("Choices must be a data.frame")
    }
    if (validate) {
      private$.validate_choices_structure(choices)
    }
    self$choices <- choices
    private$.touch()
    invisible(self)
  },

  #' @description
  #' Get the settings sheet data.
  #' @return Data frame containing the settings sheet.
  get_settings = function() {
    self$settings
  },

  #' @description
  #' Set the settings sheet data.
  #' @param settings Data frame containing settings data.
  #' @return Invisibly returns self for method chaining.
  set_settings = function(settings) {
    if (!is.data.frame(settings)) {
      stop("Settings must be a data.frame")
    }
    self$settings <- settings
    private$.touch()
    invisible(self)
  },

  # ------------------------------------------------------------------------
  # Master / Modified Survey and Choices Accessors
  # ------------------------------------------------------------------------

  #' @description
  #' Get the master (template) survey sheet.
  #' @return Data frame containing the master survey.
  get_master_survey = function() {
    self$survey
  },

  #' @description
  #' Set the master (template) survey sheet.
  #' @param survey Data frame containing the master survey.
  #' @param validate Logical, whether to validate structure (default TRUE).
  #' @return Invisibly returns self for method chaining.
  set_master_survey = function(survey, validate = TRUE) {
    if (!is.data.frame(survey)) {
      stop("Master survey must be a data.frame")
    }
    if (validate) {
      private$.validate_survey_structure(survey)
    }
    self$survey <- survey
    private$.modified_survey <- NULL
    private$.touch()
    invisible(self)
  },

  #' @description
  #' Get the master (template) choices sheet.
  #' @return Data frame containing the master choices.
  get_master_choices = function() {
    self$choices
  },

  #' @description
  #' Set the master (template) choices sheet.
  #' @param choices Data frame containing the master choices.
  #' @param validate Logical, whether to validate structure (default TRUE).
  #' @return Invisibly returns self for method chaining.
  set_master_choices = function(choices, validate = TRUE) {
    if (!is.data.frame(choices)) {
      stop("Master choices must be a data.frame")
    }
    if (validate) {
      private$.validate_choices_structure(choices)
    }
    self$choices <- choices
    private$.modified_choices <- NULL
    private$.touch()
    invisible(self)
  },

  #' @description
  #' Get the modified (filtered) survey sheet.
  #' Returns NULL if \code{filter_survey_by_modules()} has not been called yet.
  #' @return Data frame containing the modified survey, or NULL.
  get_modified_survey = function() {
    private$.modified_survey
  },

  #' @description
  #' Get the modified (filtered) choices sheet.
  #' Returns NULL if \code{filter_choices_from_survey()} has not been called yet.
  #' @return Data frame containing the modified choices, or NULL.
  get_modified_choices = function() {
    private$.modified_choices
  },

  # ------------------------------------------------------------------------
  # Tool Modification Methods
  # ------------------------------------------------------------------------

  #' @description
  #' Change the default language stored in the settings data frame.
  #' Updates the \code{default_language} column if it exists in settings.
  #' @param language Character string for the new default language (e.g., "English", "French").
  #' @return Invisibly returns self for method chaining.
  change_default_language = function(language) {
    if (!is.character(language) || length(language) != 1 || nchar(language) == 0) {
      stop("language must be a non-empty character string")
    }
    if (nrow(self$settings) == 0) {
      # Create a single-row settings frame when none exists
      self$settings <- data.frame(
        form_title       = NA_character_,
        form_id          = NA_character_,
        version          = NA_character_,
        default_language = language,
        stringsAsFactors = FALSE
      )
    } else {
      if (!"default_language" %in% names(self$settings)) {
        self$settings[["default_language"]] <- NA_character_
      }
      self$settings[["default_language"]] <- language
    }
    private$.touch()
    invisible(self)
  },

  #' @description
  #' Filter the master survey by a list or vector of module/indicator values
  #' and save the result in the modified survey field.
  #'
  #' Rows whose filter column value matches one of the provided \code{modules}
  #' are retained. Structural rows (begin/end group, begin/end repeat, note,
  #' calculate, and metadata types) are always included regardless of their
  #' filter column value.
  #'
  #' @param modules Character vector of module or sector values to include
  #'   (e.g., \code{c("core", "FSL", "WASH")}).
  #' @param filter_col Character. Name of the column used for filtering.
  #'   If NULL, the first column of the master survey is used.
  #' @return Invisibly returns self for method chaining.
  filter_survey_by_modules = function(modules, filter_col = NULL) {
    if (!is.character(modules) || length(modules) == 0) {
      stop("modules must be a non-empty character vector")
    }

    survey <- self$survey

    if (nrow(survey) == 0) {
      private$.modified_survey <- survey
      private$.touch()
      return(invisible(self))
    }

    # Determine filter column
    if (is.null(filter_col)) {
      filter_col <- names(survey)[1]
    }
    if (!filter_col %in% names(survey)) {
      stop(paste("Filter column", filter_col, "not found in master survey"))
    }

    # Structural question types that are always included
    structural_types <- c(
      "begin_group", "end_group", "begin_repeat", "end_repeat",
      "note", "calculate", "start", "end", "today",
      "deviceid", "username", "audit", "phonenumber",
      "simserial", "subscriberid"
    )

    is_structural <- if ("type" %in% names(survey)) {
      base_types <- gsub("\\s+.*$", "", survey$type)
      base_types %in% structural_types | is.na(base_types) | base_types == ""
    } else {
      rep(FALSE, nrow(survey))
    }

    col_vals <- survey[[filter_col]]
    is_selected <- !is.na(col_vals) & col_vals %in% modules

    private$.modified_survey <- survey[is_structural | is_selected, , drop = FALSE]
    private$.touch()
    invisible(self)
  },

  #' @description
  #' Filter the master choices dataframe by the choice lists referenced in
  #' the modified survey and save the result in the modified choices field.
  #'
  #' Choice list names are extracted from the \code{type} column of the
  #' modified survey: for \code{select_one} and \code{select_multiple}
  #' questions the list name follows the type keyword (e.g.,
  #' \code{"select_one yes_no"} -> \code{"yes_no"}).
  #'
  #' @return Invisibly returns self for method chaining.
  filter_choices_from_survey = function() {
    if (is.null(private$.modified_survey)) {
      stop("Call filter_survey_by_modules() before filter_choices_from_survey()")
    }

    modified_survey <- private$.modified_survey

    if (!"type" %in% names(modified_survey) || nrow(modified_survey) == 0) {
      private$.modified_choices <- self$choices[0L, , drop = FALSE]
      private$.touch()
      return(invisible(self))
    }

    # Extract choice list names from select_one / select_multiple types
    select_types <- modified_survey$type[grepl("^select_", modified_survey$type,
                                               ignore.case = FALSE)]
    list_names <- gsub("^select_(one|multiple)\\s+", "", select_types,
                       ignore.case = TRUE)
    list_names <- gsub("\\s+.*$", "", list_names)
    list_names <- unique(list_names[nchar(list_names) > 0])

    if (length(list_names) == 0 || !"list_name" %in% names(self$choices)) {
      private$.modified_choices <- self$choices[0L, , drop = FALSE]
      private$.touch()
      return(invisible(self))
    }

    private$.modified_choices <- self$choices[
      self$choices$list_name %in% list_names, , drop = FALSE
    ]
    private$.touch()
    invisible(self)
  },

  #' @description
  #' Safely update a specific choice list in the modified choices with new
  #' or revised values.  The existing entries for \code{list_name} are
  #' replaced entirely with \code{new_choices}.
  #'
  #' If the modified choices have not been generated yet (i.e.,
  #' \code{filter_choices_from_survey()} has not been called), the master
  #' choices are updated instead.
  #'
  #' @param list_name Character. Name of the choice list to replace.
  #' @param new_choices Data frame with the new choice entries.  Must contain
  #'   at minimum a \code{name} column.  A \code{list_name} column will be
  #'   added/overwritten with the value of \code{list_name}.
  #' @return Invisibly returns self for method chaining.
  update_choice_list = function(list_name, new_choices) {
    if (!is.character(list_name) || length(list_name) != 1 || nchar(list_name) == 0) {
      stop("list_name must be a non-empty character string")
    }
    if (!is.data.frame(new_choices)) {
      stop("new_choices must be a data.frame")
    }
    if (!"name" %in% names(new_choices)) {
      stop("new_choices must have a 'name' column")
    }

    # Ensure list_name column is set correctly
    new_choices[["list_name"]] <- list_name

    # Determine target: modified_choices if available, else master choices
    target <- if (!is.null(private$.modified_choices)) {
      private$.modified_choices
    } else {
      self$choices
    }

    # Align columns: add any missing columns as NA
    all_cols <- union(names(target), names(new_choices))
    for (col in setdiff(all_cols, names(target))) {
      target[[col]] <- NA
    }
    for (col in setdiff(all_cols, names(new_choices))) {
      new_choices[[col]] <- NA
    }
    new_choices <- new_choices[, names(target), drop = FALSE]

    # Remove existing entries for this list and append new ones
    updated <- rbind(
      target[target$list_name != list_name, , drop = FALSE],
      new_choices
    )

    if (!is.null(private$.modified_choices)) {
      private$.modified_choices <- updated
    } else {
      self$choices <- updated
    }

    private$.touch()
    invisible(self)
  },

  #' @description
  #' Validate that every \code{select_one} / \code{select_multiple} question
  #' in the modified survey has its choice list present in the modified
  #' choices.  Results are stored in the validation errors list and can be
  #' retrieved with \code{get_validation_errors()}.
  #'
  #' If neither modified survey nor modified choices exist, the master copies
  #' are used for validation instead.
  #'
  #' @return Logical TRUE if all choice lists are satisfied, FALSE otherwise.
  validate_tool = function() {
    private$.validation_errors <- list()

    survey_to_check <- if (!is.null(private$.modified_survey)) {
      private$.modified_survey
    } else {
      self$survey
    }
    choices_to_check <- if (!is.null(private$.modified_choices)) {
      private$.modified_choices
    } else {
      self$choices
    }

    if (!"type" %in% names(survey_to_check) || nrow(survey_to_check) == 0) {
      return(TRUE)
    }

    available_lists <- if ("list_name" %in% names(choices_to_check)) {
      unique(choices_to_check$list_name)
    } else {
      character(0)
    }

    select_rows <- grep("^select_", survey_to_check$type)
    for (i in select_rows) {
      type_str  <- survey_to_check$type[i]
      list_name <- gsub("^select_(one|multiple)\\s+", "", type_str)
      list_name <- gsub("\\s+.*$", "", list_name)

      if (nchar(list_name) > 0 && !list_name %in% available_lists) {
        private$.validation_errors <- c(
          private$.validation_errors,
          list(list(
            row     = i,
            column  = "type",
            message = paste("Choice list not found in modified choices:", list_name)
          ))
        )
      }
    }

    length(private$.validation_errors) == 0
  },

  #' @description
  #' Update a value in the settings data frame.
  #' @param key Character. Column name in the settings data frame to update.
  #' @param value The new value for the setting.
  #' @return Invisibly returns self for method chaining.
  update_settings = function(key, value) {
    if (!is.character(key) || length(key) != 1 || nchar(key) == 0) {
      stop("key must be a non-empty character string")
    }
    if (nrow(self$settings) == 0) {
      # Create a single-row settings frame when none exists
      self$settings <- data.frame(
        form_title = NA_character_,
        form_id    = NA_character_,
        version    = NA_character_,
        stringsAsFactors = FALSE
      )
    }
    if (!key %in% names(self$settings)) {
      self$settings[[key]] <- NA
    }
    self$settings[[key]] <- value
    private$.touch()
    invisible(self)
  },

  # ------------------------------------------------------------------------
  # Indicator Filtering
  # ------------------------------------------------------------------------

  #' @description
  #' Get the currently selected indicators.
  #' @return Character vector of selected indicator names.
  get_selected_indicators = function() {
    private$.selected_indicators
  },

  #' @description
  #' Set the selected indicators for filtering.
  #' @param indicators Character vector of indicator names to select.
  #' @return Invisibly returns self for method chaining.
  set_selected_indicators = function(indicators) {
    if (!is.character(indicators)) {
      stop("Indicators must be a character vector")
    }
    private$.selected_indicators <- indicators
    private$.touch()
    invisible(self)
  },

  #' @description
  #' Get the survey sheet filtered by selected indicators.
  #' Filters questions based on a mapping between indicators and question names.
  #' @param indicator_mapping Named list mapping indicator names to question names.
  #' @return Data frame with filtered survey rows.
  get_filtered_survey = function(indicator_mapping = NULL) {
    if (is.null(indicator_mapping) || length(private$.selected_indicators) == 0) {
      return(self$survey)
    }

    # Get question names for selected indicators
    selected_questions <- unlist(indicator_mapping[private$.selected_indicators])
    selected_questions <- unique(selected_questions)

    if (length(selected_questions) == 0) {
      return(self$survey)
    }

    # Filter survey to include selected questions and structural elements
    survey <- self$survey
    if (!"name" %in% names(survey)) {
      return(survey)
    }

    # Always include begin/end group, begin/end repeat, notes, and calculate types
    structural_types <- c("begin_group", "end_group", "begin_repeat", "end_repeat",
                          "note", "calculate", "start", "end", "today",
                          "deviceid", "username", "audit")

    is_structural <- if ("type" %in% names(survey)) {
      survey$type %in% structural_types
    } else {
      rep(FALSE, nrow(survey))
    }

    is_selected <- survey$name %in% selected_questions

    survey[is_structural | is_selected, , drop = FALSE]
  },

  #' @description
  #' Get the choices sheet filtered to only include choice lists used by the filtered survey questions.
  #' @param indicator_mapping Named list mapping indicator names to question names.
  #' @return Data frame with filtered choices rows.
  get_filtered_choices = function(indicator_mapping = NULL) {
    filtered_survey <- self$get_filtered_survey(indicator_mapping)

    if (!"type" %in% names(filtered_survey)) {
      return(self$choices)
    }

    # Extract choice list names from select_one and select_multiple questions
    select_types <- filtered_survey$type[grepl("^select_", filtered_survey$type)]
    list_names <- gsub("^select_(one|multiple)\\s+", "", select_types)
    list_names <- gsub("\\s+.*$", "", list_names)  # Remove anything after list name
    list_names <- unique(list_names)

    if (length(list_names) == 0 || !"list_name" %in% names(self$choices)) {
      return(self$choices)
    }

    self$choices[self$choices$list_name %in% list_names, , drop = FALSE]
  },

  # ------------------------------------------------------------------------
  # XLSForm Validation
  # ------------------------------------------------------------------------

  #' @description
  #' Validate the entire XLSForm structure.
  #' Checks for required columns, valid question types, choice list references, etc.
  #' @return Logical TRUE if valid, FALSE if there are validation errors.
  validate = function() {
    private$.validation_errors <- list()

    # Validate survey sheet structure
    private$.validate_survey_content()

    # Validate choices sheet structure
    private$.validate_choices_content()

    # Validate references between survey and choices
    private$.validate_references()

    length(private$.validation_errors) == 0
  },

  #' @description
  #' Get validation errors from the last validation run.
  #' @return List of validation error messages.
  get_validation_errors = function() {
    private$.validation_errors
  },

  #' @description
  #' Check if the tool is valid (has no validation errors).
  #' @return Logical indicating validity.
  is_valid = function() {
    self$validate()
  },

  # ------------------------------------------------------------------------
  # Question and Choice Modification
  # ------------------------------------------------------------------------

  #' @description
  #' Add a question to the survey sheet.
  #' @param type Question type (e.g., "text", "integer", "select_one list_name").
  #' @param name Unique question name/variable name.
  #' @param label Question label/text shown to user.
  #' @param required Logical or string for required constraint.
  #' @param relevant Relevance expression for skip logic.
  #' @param constraint Constraint expression for validation.
  #' @param ... Additional columns to set.
  #' @return Invisibly returns self for method chaining.
  add_question = function(type, name, label,
                          required = FALSE,
                          relevant = NA,
                          constraint = NA,
                          ...) {
    if (self$has_question(name)) {
      stop(paste("Question with name", name, "already exists"))
    }

    new_row <- data.frame(
      type = type,
      name = name,
      label = label,
      required = required,
      relevant = relevant,
      constraint = constraint,
      stringsAsFactors = FALSE
    )

    # Add any additional columns
    extra_args <- list(...)
    for (col_name in names(extra_args)) {
      new_row[[col_name]] <- extra_args[[col_name]]
    }

    # Ensure all columns from existing survey are present
    for (col in names(self$survey)) {
      if (!col %in% names(new_row)) {
        new_row[[col]] <- NA
      }
    }

    self$survey <- rbind(self$survey, new_row[, names(self$survey), drop = FALSE])
    private$.touch()
    invisible(self)
  },

  #' @description
  #' Remove a question from the survey sheet.
  #' @param name Question name to remove.
  #' @return Invisibly returns self for method chaining.
  remove_question = function(name) {
    if (!self$has_question(name)) {
      warning(paste("Question", name, "not found in survey"))
      return(invisible(self))
    }

    self$survey <- self$survey[self$survey$name != name, , drop = FALSE]
    private$.touch()
    invisible(self)
  },

  #' @description
  #' Check if a question exists in the survey.
  #' @param name Question name to check.
  #' @return Logical indicating if question exists.
  has_question = function(name) {
    "name" %in% names(self$survey) && name %in% self$survey$name
  },

  #' @description
  #' Get a specific question from the survey.
  #' @param name Question name to retrieve.
  #' @return Data frame row for the question, or NULL if not found.
  get_question = function(name) {
    if (!self$has_question(name)) {
      return(NULL)
    }
    self$survey[self$survey$name == name, , drop = FALSE]
  },

  #' @description
  #' Update a question's properties.
  #' @param name Question name to update.
  #' @param ... Named arguments for columns to update.
  #' @return Invisibly returns self for method chaining.
  update_question = function(name, ...) {
    if (!self$has_question(name)) {
      stop(paste("Question", name, "not found in survey"))
    }

    updates <- list(...)
    row_idx <- which(self$survey$name == name)

    for (col_name in names(updates)) {
      if (!col_name %in% names(self$survey)) {
        self$survey[[col_name]] <- NA
      }
      self$survey[row_idx, col_name] <- updates[[col_name]]
    }

    private$.touch()
    invisible(self)
  },

  #' @description
  #' Add a choice to the choices sheet.
  #' @param list_name Name of the choice list.
  #' @param name Choice value/name.
  #' @param label Choice label shown to user.
  #' @param ... Additional columns to set.
  #' @return Invisibly returns self for method chaining.
  add_choice = function(list_name, name, label, ...) {
    new_row <- data.frame(
      list_name = list_name,
      name = name,
      label = label,
      stringsAsFactors = FALSE
    )

    # Add any additional columns
    extra_args <- list(...)
    for (col_name in names(extra_args)) {
      new_row[[col_name]] <- extra_args[[col_name]]
    }

    # Ensure all columns from existing choices are present
    for (col in names(self$choices)) {
      if (!col %in% names(new_row)) {
        new_row[[col]] <- NA
      }
    }

    self$choices <- rbind(self$choices, new_row[, names(self$choices), drop = FALSE])
    private$.touch()
    invisible(self)
  },

  #' @description
  #' Remove choices from a specific choice list.
  #' @param list_name Name of the choice list.
  #' @param name Optional specific choice name to remove. If NULL, removes all choices in list.
  #' @return Invisibly returns self for method chaining.
  remove_choice = function(list_name, name = NULL) {
    if (is.null(name)) {
      self$choices <- self$choices[self$choices$list_name != list_name, , drop = FALSE]
    } else {
      self$choices <- self$choices[
        !(self$choices$list_name == list_name & self$choices$name == name),
        , drop = FALSE
      ]
    }
    private$.touch()
    invisible(self)
  },

  #' @description
  #' Get all choices for a specific choice list.
  #' @param list_name Name of the choice list.
  #' @return Data frame with choices for the specified list.
  get_choices_for_list = function(list_name) {
    self$choices[self$choices$list_name == list_name, , drop = FALSE]
  },

  #' @description
  #' Update a choice's properties.
  #' @param list_name Name of the choice list.
  #' @param name Choice name to update.
  #' @param ... Named arguments for columns to update.
  #' @return Invisibly returns self for method chaining.
  update_choice = function(list_name, name, ...) {
    row_idx <- which(self$choices$list_name == list_name &
                     self$choices$name == name)

    if (length(row_idx) == 0) {
      stop(paste("Choice", name, "in list", list_name, "not found"))
    }

    updates <- list(...)
    for (col_name in names(updates)) {
      if (!col_name %in% names(self$choices)) {
        self$choices[[col_name]] <- NA
      }
      self$choices[row_idx, col_name] <- updates[[col_name]]
    }

    private$.touch()
    invisible(self)
  },

  #' @description
  #' Get all unique choice list names.
  #' @return Character vector of choice list names.
  get_choice_list_names = function() {
    unique(self$choices$list_name)
  },

  # ------------------------------------------------------------------------
  # Utility Methods
  # ------------------------------------------------------------------------

  #' @description
  #' Get metadata about the tool.
  #' @return Named list with tool metadata.
  get_metadata = function() {
    list(
      name = private$.name,
      tool_type = private$.tool_type,
      created_at = private$.created_at,
      modified_at = private$.modified_at,
      num_questions = nrow(self$survey),
      num_choices = nrow(self$choices),
      num_indicators = length(private$.selected_indicators),
      custom = private$.metadata
    )
  },

  #' @description
  #' Set custom metadata.
  #' @param key Metadata key.
  #' @param value Metadata value.
  #' @return Invisibly returns self for method chaining.
  set_metadata = function(key, value) {
    private$.metadata[[key]] <- value
    private$.touch()
    invisible(self)
  },

  #' @description
  #' Clone the tool object.
  #' @param deep Logical for deep clone (default TRUE).
  #' @return A new Tool object with copied data.
  clone_tool = function(deep = TRUE) {
    new_tool <- Tool$new(
      name = paste(private$.name, "(copy)"),
      survey = if (deep) data.frame(self$survey) else self$survey,
      choices = if (deep) data.frame(self$choices) else self$choices,
      settings = if (deep) data.frame(self$settings) else self$settings
    )
    new_tool$set_selected_indicators(private$.selected_indicators)
    new_tool
  },

  #' @description
  #' Print summary of the tool.
  print = function() {
    cat("XLSForm Tool\n")
    cat("--------------------\n")
    cat("Name:", private$.name, "\n")
    cat("Type:", private$.tool_type, "\n")
    cat("Created:", format(private$.created_at, "%Y-%m-%d %H:%M:%S"), "\n")
    cat("Modified:", format(private$.modified_at, "%Y-%m-%d %H:%M:%S"), "\n")
    cat("Master Survey Questions:", nrow(self$survey), "\n")
    cat("Master Choice Lists:", length(unique(self$choices$list_name)), "\n")
    if (!is.null(private$.modified_survey)) {
      cat("Modified Survey Questions:", nrow(private$.modified_survey), "\n")
    }
    if (!is.null(private$.modified_choices)) {
      cat("Modified Choice Lists:", length(unique(private$.modified_choices$list_name)), "\n")
    }
    cat("Selected Indicators:", length(private$.selected_indicators), "\n")

    if (length(private$.validation_errors) > 0) {
      cat("\nValidation Errors:", length(private$.validation_errors), "\n")
    }

    invisible(self)
  }
),

private = list(
  .name = NULL,
  .tool_type = NULL,
  .created_at = NULL,
  .modified_at = NULL,
  .modified_survey = NULL,
  .modified_choices = NULL,
  .selected_indicators = NULL,
  .validation_errors = NULL,
  .metadata = NULL,

  # Update modification timestamp
  .touch = function() {
    private$.modified_at <- Sys.time()
  },

  # Load a default XLSForm from an xlsx file.
  # Reads the survey, choices, and settings sheets (if present) and stores
  # them as the master copies.  Called by subclass constructors.
  .load_default_tool = function(path) {
    if (!file.exists(path)) {
      warning(paste("Default tool file not found:", path))
      return(invisible(NULL))
    }

    available_sheets <- tryCatch(
      readxl::excel_sheets(path),
      error = function(e) {
        warning(paste("Could not read sheets from", path, ":", conditionMessage(e)))
        return(character(0))
      }
    )

    if ("survey" %in% available_sheets) {
      sv <- tryCatch(
        as.data.frame(readxl::read_excel(path, sheet = "survey")),
        error = function(e) {
          warning(paste("Could not read survey sheet:", conditionMessage(e)))
          NULL
        }
      )
      if (!is.null(sv)) {
        self$survey <- sv
      }
    }

    if ("choices" %in% available_sheets) {
      ch <- tryCatch(
        as.data.frame(readxl::read_excel(path, sheet = "choices")),
        error = function(e) {
          warning(paste("Could not read choices sheet:", conditionMessage(e)))
          NULL
        }
      )
      if (!is.null(ch)) {
        self$choices <- ch
      }
    }

    if ("settings" %in% available_sheets) {
      st <- tryCatch(
        as.data.frame(readxl::read_excel(path, sheet = "settings")),
        error = function(e) {
          warning(paste("Could not read settings sheet:", conditionMessage(e)))
          NULL
        }
      )
      if (!is.null(st)) {
        self$settings <- st
      }
    }

    invisible(NULL)
  },

  # Create empty survey data frame with required XLSForm columns
  .create_empty_survey = function() {
    data.frame(
      type = character(0),
      name = character(0),
      label = character(0),
      hint = character(0),
      required = character(0),
      relevant = character(0),
      constraint = character(0),
      constraint_message = character(0),
      appearance = character(0),
      calculation = character(0),
      stringsAsFactors = FALSE
    )
  },

  # Create empty choices data frame with required XLSForm columns
  .create_empty_choices = function() {
    data.frame(
      list_name = character(0),
      name = character(0),
      label = character(0),
      stringsAsFactors = FALSE
    )
  },

  # Create empty settings data frame
  .create_empty_settings = function() {
    data.frame(
      form_title = character(0),
      form_id = character(0),
      version = character(0),
      stringsAsFactors = FALSE
    )
  },

  # Validate survey data frame structure
  .validate_survey_structure = function(survey) {
    required_cols <- c("type", "name")
    missing_cols <- setdiff(required_cols, names(survey))
    if (length(missing_cols) > 0) {
      stop(paste("Survey sheet missing required columns:",
                 paste(missing_cols, collapse = ", ")))
    }
  },

  # Validate choices data frame structure
  .validate_choices_structure = function(choices) {
    required_cols <- c("list_name", "name")
    missing_cols <- setdiff(required_cols, names(choices))
    if (length(missing_cols) > 0) {
      stop(paste("Choices sheet missing required columns:",
                 paste(missing_cols, collapse = ", ")))
    }
  },

  # Validate survey content
  .validate_survey_content = function() {
    survey <- self$survey

    if (nrow(survey) == 0) {
      return(invisible(NULL))
    }

    # Check for valid question types
    valid_types <- c(
      # Basic input types
      "text", "integer", "decimal", "range",
      "note", "date", "time", "dateTime",
      "geopoint", "geotrace", "geoshape",
      "barcode", "image", "audio", "video", "file",
      # Select types (will have list_name appended)
      "select_one", "select_multiple",
      "rank",
      # Structural types
      "begin_group", "end_group",
      "begin_repeat", "end_repeat",
      # Meta types
      "start", "end", "today", "deviceid", "username",
      "phonenumber", "simserial", "subscriberid", "audit",
      # Other
      "calculate", "acknowledge", "hidden"
    )

    for (i in seq_len(nrow(survey))) {
      row_type <- survey$type[i]
      if (is.na(row_type) || row_type == "") {
        private$.validation_errors <- c(
          private$.validation_errors,
          list(list(
            row = i,
            column = "type",
            message = "Question type is missing or empty"
          ))
        )
        next
      }

      # Extract base type (before any list_name for select types)
      base_type <- gsub("\\s+.*$", "", row_type)

      if (!base_type %in% valid_types) {
        private$.validation_errors <- c(
          private$.validation_errors,
          list(list(
            row = i,
            column = "type",
            message = paste("Invalid question type:", row_type)
          ))
        )
      }
    }

    # Check for duplicate names
    if ("name" %in% names(survey)) {
      names_valid <- !is.na(survey$name) & survey$name != ""
      valid_names <- survey$name[names_valid]
      dup_names <- valid_names[duplicated(valid_names)]
      if (length(dup_names) > 0) {
        private$.validation_errors <- c(
          private$.validation_errors,
          list(list(
            row = NA,
            column = "name",
            message = paste("Duplicate question names:", paste(unique(dup_names), collapse = ", "))
          ))
        )
      }
    }

    # Check for balanced groups
    if ("type" %in% names(survey)) {
      begin_groups <- sum(survey$type == "begin_group", na.rm = TRUE)
      end_groups <- sum(survey$type == "end_group", na.rm = TRUE)
      if (begin_groups != end_groups) {
        private$.validation_errors <- c(
          private$.validation_errors,
          list(list(
            row = NA,
            column = "type",
            message = paste("Unbalanced groups: ", begin_groups, "begin_group vs",
                            end_groups, "end_group")
          ))
        )
      }

      # Check for balanced repeats
      begin_repeats <- sum(survey$type == "begin_repeat", na.rm = TRUE)
      end_repeats <- sum(survey$type == "end_repeat", na.rm = TRUE)
      if (begin_repeats != end_repeats) {
        private$.validation_errors <- c(
          private$.validation_errors,
          list(list(
            row = NA,
            column = "type",
            message = paste("Unbalanced repeats: ", begin_repeats, "begin_repeat vs",
                            end_repeats, "end_repeat")
          ))
        )
      }
    }
  },

  # Validate choices content
  .validate_choices_content = function() {
    choices <- self$choices

    if (nrow(choices) == 0) {
      return(invisible(NULL))
    }

    # Check for duplicate choices within each list
    for (list_name in unique(choices$list_name)) {
      list_choices <- choices[choices$list_name == list_name, ]
      dup_names <- list_choices$name[duplicated(list_choices$name)]
      if (length(dup_names) > 0) {
        private$.validation_errors <- c(
          private$.validation_errors,
          list(list(
            row = NA,
            column = "name",
            message = paste("Duplicate choice names in list", list_name, ":",
                            paste(unique(dup_names), collapse = ", "))
          ))
        )
      }
    }
  },

  # Validate references between survey and choices
  .validate_references = function() {
    survey <- self$survey
    choices <- self$choices

    if (!"type" %in% names(survey)) {
      return(invisible(NULL))
    }

    # Check that select questions reference valid choice lists
    select_rows <- grep("^select_", survey$type)

    for (i in select_rows) {
      type_str <- survey$type[i]
      # Extract list name from type (e.g., "select_one yes_no" -> "yes_no")
      list_name <- gsub("^select_(one|multiple)\\s+", "", type_str)
      list_name <- gsub("\\s+.*$", "", list_name)  # Remove any following text

      if (nchar(list_name) > 0 && !list_name %in% choices$list_name) {
        private$.validation_errors <- c(
          private$.validation_errors,
          list(list(
            row = i,
            column = "type",
            message = paste("Choice list not found:", list_name)
          ))
        )
      }
    }
  }
)
)



